services:
  - type: web
    name: playground-playgroup-swap
    env: docker
    autoDeploy: true
    dockerfilePath: apps/playground-playgroup-swap/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
